# Makefile for build 'rawdev' in Linux/MacOs/BSD
# Generated by the 'makemake.sh' script
# Dependencies generated with 'g++ -MM'
# Čt 15. června 2023, 14:05:00 CEST

PROGRAM = rawdev
BUILD_DIR = build/maked
OBJ_DIR = $(BUILD_DIR)/obj

# Use clang++ for MacOS and BSD (for Linux use GCC)
# CC = clang++

# Use GCC for Linux
CC = g++

# Compiler flags (O3 causes warnings on GCC)
CCFLAGS = -std=c++14 -Wall -pedantic -O2 -fopenmp -I src/

OBJECTS = \
	$(OBJ_DIR)/CamProfile.o \
	$(OBJ_DIR)/CFAPattern.o \
	$(OBJ_DIR)/Cam5D.o \
	$(OBJ_DIR)/Cam5Ds.o \
	$(OBJ_DIR)/Cam5DsR.o \
	$(OBJ_DIR)/Cam5D2.o \
	$(OBJ_DIR)/Cam5D3.o \
	$(OBJ_DIR)/Cam5D4.o \
	$(OBJ_DIR)/Cam6D.o \
	$(OBJ_DIR)/Cam6D2.o \
	$(OBJ_DIR)/Cam7D.o \
	$(OBJ_DIR)/Cam7D2.o \
	$(OBJ_DIR)/CmdLineParser.o \
	$(OBJ_DIR)/Color.o \
	$(OBJ_DIR)/AdobeRGB1998-icc.o \
	$(OBJ_DIR)/srgb-icc.o \
	$(OBJ_DIR)/AHD.o \
	$(OBJ_DIR)/Bilinear.o \
	$(OBJ_DIR)/Demosaic.o \
	$(OBJ_DIR)/Freeman.o \
	$(OBJ_DIR)/HQLinear.o \
	$(OBJ_DIR)/Denoise.o \
	$(OBJ_DIR)/ByteTag.o \
	$(OBJ_DIR)/CR2Reader.o \
	$(OBJ_DIR)/HuffTree.o \
	$(OBJ_DIR)/LongTag.o \
	$(OBJ_DIR)/RationalTag.o \
	$(OBJ_DIR)/ShortTag.o \
	$(OBJ_DIR)/StringTag.o \
	$(OBJ_DIR)/TagFactory.o \
	$(OBJ_DIR)/TiffDir.o \
	$(OBJ_DIR)/TiffWriter.o \
	$(OBJ_DIR)/Logger.o \
	$(OBJ_DIR)/Main.o \
	$(OBJ_DIR)/Options.o \
	$(OBJ_DIR)/Output.o \
	$(OBJ_DIR)/ProcRGB.o \
	$(OBJ_DIR)/RawDev.o \
	$(OBJ_DIR)/Scale.o \
	$(OBJ_DIR)/HSVMap.o \
	$(OBJ_DIR)/Image.o \
	$(OBJ_DIR)/Mat3x3.o \
	$(OBJ_DIR)/Path.o \
	$(OBJ_DIR)/Utils.o

all: prepare $(BUILD_DIR)/$(PROGRAM)
	@echo 'DONE!'

prepare:
	@mkdir -p $(BUILD_DIR)/obj

clear:
	rm -rf $(BUILD_DIR)

.PHONY: all prepare clear

#########

$(BUILD_DIR)/$(PROGRAM): $(OBJECTS)
	$(CC) $(CCFLAGS) -o $@ $?

$(OBJ_DIR)/CamProfile.o: src/CamProfiles/CamProfile.cpp \
 src/CamProfiles/CamProfile.hpp src/Color.hpp src/Structures/Rect.hpp \
 src/Structures/Mat3x3.hpp src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp \
 src/CamProfiles/EOS_5D/Cam5D.hpp src/CamProfiles/EOS_5D2/Cam5D2.hpp \
 src/CamProfiles/EOS_5D3/Cam5D3.hpp src/CamProfiles/EOS_5D4/Cam5D4.hpp \
 src/CamProfiles/EOS_5Ds/Cam5Ds.hpp src/CamProfiles/EOS_5DsR/Cam5DsR.hpp \
 src/CamProfiles/EOS_6D/Cam6D.hpp src/CamProfiles/EOS_6D2/Cam6D2.hpp \
 src/CamProfiles/EOS_7D/Cam7D.hpp src/CamProfiles/EOS_7D2/Cam7D2.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/CamProfile.cpp

$(OBJ_DIR)/CFAPattern.o: src/CamProfiles/CFAPattern.cpp \
 src/CamProfiles/CFAPattern.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/CFAPattern.cpp

$(OBJ_DIR)/Cam5D.o: src/CamProfiles/EOS_5D/Cam5D.cpp \
 src/CamProfiles/EOS_5D/Cam5D.hpp src/CamProfiles/CamProfile.hpp \
 src/Color.hpp src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Utils.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/EOS_5D/Cam5D.cpp

$(OBJ_DIR)/Cam5Ds.o: src/CamProfiles/EOS_5Ds/Cam5Ds.cpp \
 src/CamProfiles/EOS_5Ds/Cam5Ds.hpp src/CamProfiles/CamProfile.hpp \
 src/Color.hpp src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Utils.hpp \
 src/CamProfiles/EOS_5Ds/hsvMap1.hpp src/CamProfiles/EOS_5Ds/hsvMap2.hpp \
 src/CamProfiles/EOS_5Ds/profLookMap.hpp \
 src/CamProfiles/EOS_5Ds/toneCurve.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/EOS_5Ds/Cam5Ds.cpp

$(OBJ_DIR)/Cam5DsR.o: src/CamProfiles/EOS_5DsR/Cam5DsR.cpp \
 src/CamProfiles/EOS_5DsR/Cam5DsR.hpp src/CamProfiles/CamProfile.hpp \
 src/Color.hpp src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Utils.hpp \
 src/CamProfiles/EOS_5DsR/hsvMap1.hpp \
 src/CamProfiles/EOS_5DsR/hsvMap2.hpp \
 src/CamProfiles/EOS_5DsR/profLookMap.hpp \
 src/CamProfiles/EOS_5DsR/toneCurve.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/EOS_5DsR/Cam5DsR.cpp

$(OBJ_DIR)/Cam5D2.o: src/CamProfiles/EOS_5D2/Cam5D2.cpp \
 src/CamProfiles/EOS_5D2/Cam5D2.hpp src/CamProfiles/CamProfile.hpp \
 src/Color.hpp src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Utils.hpp \
 src/CamProfiles/EOS_5D2/profLookMap.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/EOS_5D2/Cam5D2.cpp

$(OBJ_DIR)/Cam5D3.o: src/CamProfiles/EOS_5D3/Cam5D3.cpp \
 src/CamProfiles/EOS_5D3/Cam5D3.hpp src/CamProfiles/CamProfile.hpp \
 src/Color.hpp src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Utils.hpp \
 src/CamProfiles/EOS_5D3/hsvMap1.hpp src/CamProfiles/EOS_5D3/hsvMap2.hpp \
 src/CamProfiles/EOS_5D3/profLookMap.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/EOS_5D3/Cam5D3.cpp

$(OBJ_DIR)/Cam5D4.o: src/CamProfiles/EOS_5D4/Cam5D4.cpp \
 src/CamProfiles/EOS_5D4/Cam5D4.hpp src/CamProfiles/CamProfile.hpp \
 src/Color.hpp src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Utils.hpp \
 src/CamProfiles/EOS_5D4/hsvMap1.hpp src/CamProfiles/EOS_5D4/hsvMap2.hpp \
 src/CamProfiles/EOS_5D4/profLookMap.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/EOS_5D4/Cam5D4.cpp

$(OBJ_DIR)/Cam6D.o: src/CamProfiles/EOS_6D/Cam6D.cpp \
 src/CamProfiles/EOS_6D/Cam6D.hpp src/CamProfiles/CamProfile.hpp \
 src/Color.hpp src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Utils.hpp \
 src/CamProfiles/EOS_6D/hsvMap1.hpp src/CamProfiles/EOS_6D/hsvMap2.hpp \
 src/CamProfiles/EOS_6D/profLookMap.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/EOS_6D/Cam6D.cpp

$(OBJ_DIR)/Cam6D2.o: src/CamProfiles/EOS_6D2/Cam6D2.cpp \
 src/CamProfiles/EOS_6D2/Cam6D2.hpp src/CamProfiles/CamProfile.hpp \
 src/Color.hpp src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Utils.hpp \
 src/CamProfiles/EOS_6D2/hsvMap1.hpp src/CamProfiles/EOS_6D2/hsvMap2.hpp \
 src/CamProfiles/EOS_6D2/profLookMap.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/EOS_6D2/Cam6D2.cpp

$(OBJ_DIR)/Cam7D.o: src/CamProfiles/EOS_7D/Cam7D.cpp \
 src/CamProfiles/EOS_7D/Cam7D.hpp src/CamProfiles/CamProfile.hpp \
 src/Color.hpp src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Utils.hpp \
 src/CamProfiles/EOS_7D/profLookMap.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/EOS_7D/Cam7D.cpp

$(OBJ_DIR)/Cam7D2.o: src/CamProfiles/EOS_7D2/Cam7D2.cpp \
 src/CamProfiles/EOS_7D2/Cam7D2.hpp src/CamProfiles/CamProfile.hpp \
 src/Color.hpp src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Utils.hpp \
 src/CamProfiles/EOS_7D2/hsvMap1.hpp src/CamProfiles/EOS_7D2/hsvMap2.hpp \
 src/CamProfiles/EOS_7D2/profLookMap.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CamProfiles/EOS_7D2/Cam7D2.cpp

$(OBJ_DIR)/CmdLineParser.o: src/CmdLineParser.cpp src/CmdLineParser.hpp \
 src/CmdLineArgument.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/CmdLineParser.cpp

$(OBJ_DIR)/Color.o: src/Color.cpp src/Color.hpp src/Utils.hpp \
 src/Structures/Mat3x3.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Color.cpp

$(OBJ_DIR)/AdobeRGB1998-icc.o: src/ColorProfiles/AdobeRGB1998-icc.cpp \
 src/ColorProfiles/AdobeRGB1998-icc.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ColorProfiles/AdobeRGB1998-icc.cpp

$(OBJ_DIR)/srgb-icc.o: src/ColorProfiles/srgb-icc.cpp src/ColorProfiles/srgb-icc.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ColorProfiles/srgb-icc.cpp

$(OBJ_DIR)/AHD.o: src/Demosaic/AHD.cpp src/Demosaic/AHD.hpp \
 src/Demosaic/Algorithm.hpp src/Structures/Image.hpp src/NonCopyable.hpp \
 src/Color.hpp src/Structures/Array2D.hpp src/Utils.hpp \
 src/Structures/Mat3x3.hpp src/CamProfiles/CamProfile.hpp \
 src/Structures/Rect.hpp src/Structures/HSVMap.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Logger.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Demosaic/AHD.cpp

$(OBJ_DIR)/Bilinear.o: src/Demosaic/Bilinear.cpp src/Demosaic/Bilinear.hpp \
 src/Demosaic/Algorithm.hpp src/Structures/Image.hpp src/NonCopyable.hpp \
 src/Color.hpp src/Structures/Array2D.hpp src/Utils.hpp \
 src/CamProfiles/CamProfile.hpp src/Structures/Rect.hpp \
 src/Structures/Mat3x3.hpp src/Structures/HSVMap.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Logger.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Demosaic/Bilinear.cpp

$(OBJ_DIR)/Demosaic.o: src/Demosaic.cpp src/Demosaic.hpp src/Options.hpp \
 src/Structures/Path.hpp src/Demosaic/AlgorithmType.hpp \
 src/ColorProfiles/ColorProfile.hpp src/StopWatch.hpp src/Logger.hpp \
 src/RawDev.hpp src/Demosaic/Bilinear.hpp src/Demosaic/Algorithm.hpp \
 src/Demosaic/Freeman.hpp src/Structures/Rect.hpp \
 src/Demosaic/HQLinear.hpp src/Demosaic/AHD.hpp src/Structures/Image.hpp \
 src/NonCopyable.hpp src/Color.hpp src/Structures/Array2D.hpp \
 src/Utils.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Demosaic.cpp

$(OBJ_DIR)/Freeman.o: src/Demosaic/Freeman.cpp src/Demosaic/Freeman.hpp \
 src/Demosaic/Algorithm.hpp src/Structures/Rect.hpp \
 src/Demosaic/Bilinear.hpp src/Structures/Image.hpp src/NonCopyable.hpp \
 src/Color.hpp src/Structures/Array2D.hpp src/Utils.hpp \
 src/CamProfiles/CamProfile.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/CamProfiles/CFAPattern.hpp \
 src/CamProfiles/CamID.hpp src/Logger.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Demosaic/Freeman.cpp

$(OBJ_DIR)/HQLinear.o: src/Demosaic/HQLinear.cpp src/Demosaic/HQLinear.hpp \
 src/Demosaic/Algorithm.hpp src/Structures/Image.hpp src/NonCopyable.hpp \
 src/Color.hpp src/Structures/Array2D.hpp src/Utils.hpp \
 src/Structures/Rect.hpp src/CamProfiles/CamProfile.hpp \
 src/Structures/Mat3x3.hpp src/Structures/HSVMap.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Logger.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Demosaic/HQLinear.cpp

$(OBJ_DIR)/Denoise.o: src/Denoise.cpp src/Denoise.hpp src/Structures/Image.hpp \
 src/NonCopyable.hpp src/Color.hpp src/Structures/Array2D.hpp \
 src/Utils.hpp src/Options.hpp src/Structures/Path.hpp \
 src/Demosaic/AlgorithmType.hpp src/ColorProfiles/ColorProfile.hpp \
 src/RawDev.hpp src/Logger.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Denoise.cpp

$(OBJ_DIR)/ByteTag.o: src/ImageIO/ByteTag.cpp src/ImageIO/ByteTag.hpp \
 src/ImageIO/TiffTag.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ImageIO/ByteTag.cpp

$(OBJ_DIR)/CR2Reader.o: src/ImageIO/CR2Reader.cpp src/ImageIO/CR2Reader.hpp \
 src/NonCopyable.hpp src/Structures/Array2D.hpp src/Color.hpp \
 src/Utils.hpp src/ImageIO/TiffDir.hpp src/ImageIO/TiffTag.hpp \
 src/ImageIO/LongTag.hpp src/ImageIO/ShortTag.hpp \
 src/ImageIO/StringTag.hpp src/ImageIO/TiffHeader.hpp \
 src/ImageIO/RawHeader.hpp src/ImageIO/HuffTree.hpp src/Exception.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ImageIO/CR2Reader.cpp

$(OBJ_DIR)/HuffTree.o: src/ImageIO/HuffTree.cpp src/ImageIO/HuffTree.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ImageIO/HuffTree.cpp

$(OBJ_DIR)/LongTag.o: src/ImageIO/LongTag.cpp src/ImageIO/LongTag.hpp \
 src/ImageIO/TiffTag.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ImageIO/LongTag.cpp

$(OBJ_DIR)/RationalTag.o: src/ImageIO/RationalTag.cpp src/ImageIO/RationalTag.hpp \
 src/ImageIO/TiffTag.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ImageIO/RationalTag.cpp

$(OBJ_DIR)/ShortTag.o: src/ImageIO/ShortTag.cpp src/ImageIO/ShortTag.hpp \
 src/ImageIO/TiffTag.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ImageIO/ShortTag.cpp

$(OBJ_DIR)/StringTag.o: src/ImageIO/StringTag.cpp src/ImageIO/StringTag.hpp \
 src/ImageIO/TiffTag.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ImageIO/StringTag.cpp

$(OBJ_DIR)/TagFactory.o: src/ImageIO/TagFactory.cpp src/ImageIO/TagFactory.hpp \
 src/ImageIO/TiffTag.hpp src/ImageIO/StringTag.hpp \
 src/ImageIO/ShortTag.hpp src/ImageIO/LongTag.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ImageIO/TagFactory.cpp

$(OBJ_DIR)/TiffDir.o: src/ImageIO/TiffDir.cpp src/ImageIO/TiffDir.hpp \
 src/ImageIO/TiffTag.hpp src/ImageIO/LongTag.hpp src/ImageIO/ShortTag.hpp \
 src/ImageIO/StringTag.hpp src/ImageIO/TagFactory.hpp src/Utils.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ImageIO/TiffDir.cpp

$(OBJ_DIR)/TiffWriter.o: src/ImageIO/TiffWriter.cpp src/ImageIO/TiffWriter.hpp \
 src/ImageIO/TiffDir.hpp src/ImageIO/TiffTag.hpp src/ImageIO/LongTag.hpp \
 src/ImageIO/ShortTag.hpp src/ImageIO/StringTag.hpp src/NonCopyable.hpp \
 src/Structures/Image.hpp src/Color.hpp src/Structures/Array2D.hpp \
 src/Utils.hpp src/ImageIO/TiffHeader.hpp src/ImageIO/ByteTag.hpp \
 src/ImageIO/RationalTag.hpp src/Structures/Rect.hpp \
 src/CamProfiles/CamProfile.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/CamProfiles/CFAPattern.hpp \
 src/CamProfiles/CamID.hpp src/Exception.hpp \
 src/ColorProfiles/ColorProfile.hpp \
 src/ColorProfiles/AdobeRGB1998-icc.hpp src/ColorProfiles/srgb-icc.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ImageIO/TiffWriter.cpp

$(OBJ_DIR)/Logger.o: src/Logger.cpp src/Logger.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Logger.cpp

$(OBJ_DIR)/Main.o: src/Main.cpp src/RawDev.hpp src/Options.hpp \
 src/Structures/Path.hpp src/Demosaic/AlgorithmType.hpp \
 src/ColorProfiles/ColorProfile.hpp src/Logger.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Main.cpp

$(OBJ_DIR)/Options.o: src/Options.cpp src/Options.hpp src/Structures/Path.hpp \
 src/Demosaic/AlgorithmType.hpp src/ColorProfiles/ColorProfile.hpp \
 src/CmdLineParser.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Options.cpp

$(OBJ_DIR)/Output.o: src/Output.cpp src/Output.hpp src/Structures/Path.hpp \
 src/Structures/Image.hpp src/NonCopyable.hpp src/Color.hpp \
 src/Structures/Array2D.hpp src/Utils.hpp src/Options.hpp \
 src/Demosaic/AlgorithmType.hpp src/ColorProfiles/ColorProfile.hpp \
 src/RawDev.hpp src/Logger.hpp src/CamProfiles/CamProfile.hpp \
 src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/CamProfiles/CFAPattern.hpp \
 src/CamProfiles/CamID.hpp src/Structures/LUT.hpp \
 src/ImageIO/TiffWriter.hpp src/ImageIO/TiffDir.hpp \
 src/ImageIO/TiffTag.hpp src/ImageIO/LongTag.hpp src/ImageIO/ShortTag.hpp \
 src/ImageIO/StringTag.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Output.cpp

$(OBJ_DIR)/ProcRGB.o: src/ProcRGB.cpp src/ProcRGB.hpp src/Structures/Image.hpp \
 src/NonCopyable.hpp src/Color.hpp src/Structures/Array2D.hpp \
 src/Utils.hpp src/CamProfiles/CamProfile.hpp src/Structures/Rect.hpp \
 src/Structures/Mat3x3.hpp src/Structures/HSVMap.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp src/Options.hpp \
 src/Structures/Path.hpp src/Demosaic/AlgorithmType.hpp \
 src/ColorProfiles/ColorProfile.hpp src/RawDev.hpp src/Logger.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/ProcRGB.cpp

$(OBJ_DIR)/RawDev.o: src/RawDev.cpp src/RawDev.hpp src/Options.hpp \
 src/Structures/Path.hpp src/Demosaic/AlgorithmType.hpp \
 src/ColorProfiles/ColorProfile.hpp src/Logger.hpp \
 src/Structures/Image.hpp src/NonCopyable.hpp src/Color.hpp \
 src/Structures/Array2D.hpp src/Utils.hpp src/CamProfiles/CamProfile.hpp \
 src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/CamProfiles/CFAPattern.hpp \
 src/CamProfiles/CamID.hpp src/CmdLineParser.hpp src/StopWatch.hpp \
 src/Exception.hpp src/Scale.hpp src/Denoise.hpp src/Demosaic.hpp \
 src/ProcRGB.hpp src/Output.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/RawDev.cpp

$(OBJ_DIR)/Scale.o: src/Scale.cpp src/Scale.hpp src/Color.hpp \
 src/CamProfiles/CamProfile.hpp src/Structures/Rect.hpp \
 src/Structures/Mat3x3.hpp src/Structures/HSVMap.hpp src/NonCopyable.hpp \
 src/CamProfiles/CFAPattern.hpp src/CamProfiles/CamID.hpp \
 src/Structures/Image.hpp src/Structures/Array2D.hpp src/Utils.hpp \
 src/Options.hpp src/Structures/Path.hpp src/Demosaic/AlgorithmType.hpp \
 src/ColorProfiles/ColorProfile.hpp src/RawDev.hpp src/Logger.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Scale.cpp

$(OBJ_DIR)/HSVMap.o: src/Structures/HSVMap.cpp src/Structures/HSVMap.hpp \
 src/NonCopyable.hpp src/Color.hpp src/Utils.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Structures/HSVMap.cpp

$(OBJ_DIR)/Image.o: src/Structures/Image.cpp src/Structures/Image.hpp \
 src/NonCopyable.hpp src/Color.hpp src/Structures/Array2D.hpp \
 src/Utils.hpp src/ImageIO/CR2Reader.hpp src/ImageIO/TiffDir.hpp \
 src/ImageIO/TiffTag.hpp src/ImageIO/LongTag.hpp src/ImageIO/ShortTag.hpp \
 src/ImageIO/StringTag.hpp src/CamProfiles/CamProfile.hpp \
 src/Structures/Rect.hpp src/Structures/Mat3x3.hpp \
 src/Structures/HSVMap.hpp src/CamProfiles/CFAPattern.hpp \
 src/CamProfiles/CamID.hpp src/Structures/Path.hpp src/Exception.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Structures/Image.cpp

$(OBJ_DIR)/Mat3x3.o: src/Structures/Mat3x3.cpp src/Structures/Mat3x3.hpp \
 src/Color.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Structures/Mat3x3.cpp

$(OBJ_DIR)/Path.o: src/Structures/Path.cpp src/Structures/Path.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Structures/Path.cpp

$(OBJ_DIR)/Utils.o: src/Utils.cpp src/Utils.hpp src/Color.hpp \
 src/Structures/Mat3x3.hpp
	$(CC) $(CCFLAGS) -c -o $@ src/Utils.cpp

