name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  RAWDEV_BUILD_PATH: ${{ github.workspace }}/build

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure with CMake
        run: >
          cmake
          -B ${{ env.RAWDEV_BUILD_PATH }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: >
          cmake
          --build ${{ env.RAWDEV_BUILD_PATH }}
          --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ env.RAWDEV_BUILD_PATH }}
        run: ctest --build-config ${{ matrix.build_type }}
